language: ruby

cache:
 bundler: true
 directories:
  - node_modules
  - vendor/assets/bower_components

rvm:
  - 2.3.0

before_script:
  - ./bin/rake db:create RAILS_ENV=test
  - ./bin/rake ridgepole:apply RAILS_ENV=test
  - npm install -g bower
  - ./bin/rake bower:install
