default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dmemo_development

test:
  <<: *default
  database: dmemo_test

production:
  <<: *default
  database: dmemo_development

